### ISSUE TITLE
GLY being output with CB atom

### ISSUE THREAD

**Issue by SenyorDrew** [brennanaba/ABlooper#3]
Thanks for contributing a great tool like this.  
I noticed that GLY residues were being output with a CB atom present.  Not sure if this is a bug, but on line 134 of ABlooper.py, you have:

`if (j==4) and (amino_type == "GLY"):`
I'm wondering if it should be:
`if (j==3) and (amino_type == "GLY"):`

Thanks!

**Comment by brennanaba** [comment]
Hi Senyor,

I think I have fixed this now. I tried to make it a bit more readable too.

Let me know if you encounter any other bugs.

Thanks!!
