### ISSUE TITLE
Does Ablooper only model backbone atoms?

### ISSUE THREAD

**Issue by drewaight** [brennanaba/ABlooper#4]
Sorry its a little unclear from the paper or the documentation whether the full atom CDRs are modeled. I seem to only have the backbone atoms in the output pdb. Thanks very much! Excellent work!

**Comment by brennanaba** [comment]
Hi @drewaight,
Yes, you are right. It only predicts the N-CA-C-CB atoms of the backbone. Sorry if this wasn't very clear. I will change the documentation to explicitly state this.

**Comment by brennanaba** [comment]
@drewaight In case you are interested, I added some code for side-chain prediction with PyRosetta.

**Comment by drewaight** [comment]
Thanks for the heads up! I'll check it out.
