### ISSUE TITLE
Bug in generating ATOM lines from ABlooper Coordinate Output

### ISSUE THREAD

**Issue by BYachnin** [brennanaba/ABlooper#5]
Hi.  I've noticed a bug in how ABlooper post-processes the numpy coordinates into PDB `ATOM` records.  The issue is somewhat obscure, as I think it will only occur if one or more of the coordinates is less than or equal to -100.

According to the PDB standard for `ATOM` records, the coordinate fields should be 8 characters wide, with *no* spaces between x, y, and z, and with three decimal places.  The way you have it right now, the coordinates are 7 characters wide, with *one* space between x, y, and z.  See https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

I think that most coordinates end up being fine, as they don't occupy the full 4 characters allowed before the decimal point.  The problem occurs for large negative numbers, in which case
`-234.678`
becomes
` -234.67` (note leading space)

This triggers an offset in the line lengths and breaks parsing of the output file in some cases.

To fix it, I was able to change line 110 in https://github.com/brennanaba/ABlooper/blob/master/ABlooper/utils.py#L110 to the following:
`line = "ATOM  {:5d}  {:3s} {:3s} {:1s} {:3d}{:2s}  {:8.3f}{:8.3f}{:8.3f}  1.00  0.00           {}  \n"`

Thanks!

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Python version 3.8.5
 - PyTorch version 1.7.0

**Comment by brennanaba** [comment]
You are right. Thanks a lot @BYachnin I have fixed it now. Please let me know if you encounter any other bugs
