### ISSUE TITLE
predict H chain only?

### ISSUE THREAD

**Issue by QUEST2179** [brennanaba/ABlooper#6]
Dear developer,

How to model one chain only, for example for nanobody? Thanks!

pred = CDR_Predictor(input_path, chains = ("H", "")) #, "L"

It gave me an error:

    res = loop[i].split()[5]
IndexError: list index out of range

**Comment by brennanaba** [comment]
Hi @QUEST2179 

Sorry but ABlooper does not currently support single chain modelling.
