### ISSUE TITLE
[meta] How reliable is this tool's output? Can it be used in conjunction with free software PDB renderers to make antibody graphics for e.g. Wikipedia?

### ISSUE THREAD

**Issue by ctrlcctrlv** [brennanaba/ABlooper#9]
Can output of http://opig.stats.ox.ac.uk/webapps/newsabdab/sabpred/abodybuilder/ be replied upon for creation of educational images?

_Cf._ https://github.com/ncbi/icn3d/issues/87

**Comment by brennanaba** [comment]
Hi @ctrlcctrlv

The global structure of antibodies is mostly conserved and can be predicted with an accuracy comparable to that of experimental structures by most methods out there. The exception to this is the CDR-H3 loop which is very hard to model accurately. Structural models are routinely used in industry to make decisions in therapeutic development, so I suspect they will be accurate enough to use in an educational setting. 

I don't know how much you know about antibodies, but this method only predicts the structure of the variable region (the region responsible for binding in antibodies), so if you are trying to show the whole structure of an antibody they will not be sufficient. If you are interested in creating graphics for a full antibody, I would recommend checking out [this structure](https://www.rcsb.org/structure/1igt). 

Hope this helps!!

All the best,

Brennan
